name: snow2code_plugin
display_name: 'Test'
description: A snowy plugin
author: 'snow2code'
website: https://snow2code.infy.uk
version: ${version} # '1.0-SNAPSHOT'
main: org.snow2code.plugin.Main
api-version: '1.21'

#commands:
#  snowy:
#    description: Base command for Snowy's Plugin
#    usage: /snowy <reload>
#    aliases: [snowy]
#    # permission: snowy.admin

permissions:
  snow2code.admin:
    description: Snow2Code Admin Permission
    default: op