name: snow2code_plugin
display_name: 'Test'
description: A snowy plugin
author: 'snow2code'
website: https://snow2code.infy.uk
version: ${version}
main: org.snow2code.plugin.Snow2Code_Plugin
api-version: '1.21'
depend: [UltimateAdvancementAPI]

commands:
  mouth:
    description: Opens Snowy’s Snout Pouch or Mighty Mouth
    usage: /mouth [small|big]
#  snowy:
#    description: Base command for Snowy's Plugin
#    usage: /snowy <reload>
#    aliases: [snowy]
#    # permission: snowy.admin

permissions:
  snow2code.admin:
    description: Snow2Code Admin Permission
    default: op